global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'hunter'
    static_configs:
      - targets: ['hunter:8001']
    metrics_path: '/metrics'

  - job_name: 'judge'
    static_configs:
      - targets: ['judge:8002']
    metrics_path: '/metrics'

  - job_name: 'guard'
    static_configs:
      - targets: ['guard:8000']
    metrics_path: '/metrics'

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-exporter:9308']
