apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  labels:
    app: sentinel-db
type: Opaque
stringData:
  mongodb-url: "mongodb://sentinel:sentinel_password@sentinel-db:27017/fraud_ledger?authSource=admin"
  mongodb-username: "sentinel"
  mongodb-password: "sentinel_password"
