apiVersion: v1
kind: Service
metadata:
  name: sentinel-gateway
  labels:
    app: sentinel-gateway
    tier: api-gateway
spec:
  type: LoadBalancer
  selector:
    app: sentinel-gateway
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  sessionAffinity: None
